s3:
  drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/met/gefs-v12
  inflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/inflow/CANN/inflow-xbgoost
  targets:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/targets
  forecasts:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  warm_start:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
   site_id: CANN
   name: Swan-Canning River
   latitude: -32   #Degrees North
   longitude: 116  #Degrees East
da_setup:
    da_method: enkf
    par_fit_method: perturb_const
    ensemble_size:  100
    localization_distance: 2 #distance in meters were covariances in the model error are used
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    use_obs_constraint: TRUE
    obs_filename: CANN-targets-insitu.csv
model_settings:
   ncore: 4
   model_name: glm
   base_GLM_nml: glm3.nml
   modeled_depths: [0.0, 0.25, 0.50, 0.75, 1.0,
                    1.25, 1.50, 1.75, 2.0,
                    2.25, 2.50, 2.75, 3.0,
                    3.25, 3.50, 3.75, 4.0,
                    4.25, 4.50, 4.75, 5.0,
                    5.25, 5.50, 5.75, 6.0]
   par_config_file: parameter_calibration_config.csv
   obs_config_file: observations_config.csv
   states_config_file: states_config.csv
   depth_model_sd_config_file: depth_model_sd.csv
default_init:
   lake_depth: 6.0  #not a modeled state
   temp: [10.20,10.20,10.20,10.20]
   temp_depths: [1.5,3.0,4.5,6.0]
   salinity: 0.25
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
inflow:
   use_forecasted_inflow: TRUE
   forecast_inflow_model: inflow-xbgoost
   include_inflow: TRUE
   observed_filename: CANN-targets-inflow.csv
   inflow_variables: NA
   use_ler_vars: FALSE
   local_directory: drivers/inflow 
met:
   use_forecasted_met: TRUE
   use_observed_met: FALSE
   local_directory: .na
   observed_met_filename: CANN-targets-met.csv
   use_ler_vars: FALSE
   forecast_lag_days: 1
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   met_downscale: TRUE
   inflow_process: TRUE
output_settings:
   diagnostics_names:  [extc]
   evaluate_past: TRUE
   variables_in_scores: [state, parameter]
