s3:
  drivers:
    endpoint: s3.flare-forecast.org
    bucket: drivers/noaa/gefs-v12
  inflow_drivers:
    endpoint: s3.flare-forecast.org
    bucket: drivers/inflow/alex_v2/parquet
  targets:
    endpoint: s3.flare-forecast.org
    bucket: targets/alex_v2
  forecasts:
    endpoint: s3.flare-forecast.org
    bucket: forecasts
  forecasts_parquet:
    endpoint: s3.flare-forecast.org
    bucket: forecasts/parquet
  warm_start:
    endpoint: s3.flare-forecast.org
    bucket: restart/alex_v2
  scores:
    endpoint: s3.flare-forecast.org
    bucket: scores/parquet
location:
   site_id: ALEX
   name: Lake Alexandrina
   latitude: -35   #Degrees North
   longitude: 138  #Degrees East
da_setup:
    da_method: enkf
    par_fit_method: perturb_const
    ensemble_size:  256
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    use_obs_constraint: TRUE
    obs_filename: ALEX-targets-insitu.csv
model_settings:
   ncore: 4
   model_name: glm
   base_GLM_nml: glm3.nml
   modeled_depths: [0.0, 0.25, 0.50, 0.75, 1.0,
                    1.25, 1.50, 1.75, 2.0,
                    2.25, 2.50, 2.75, 3.0,
                    3.25, 3.50, 3.75, 4.0,
                    4.25, 4.50, 4.75, 5.0,
                    5.25, 5.50, 5.75, 6.0]
   par_config_file: parameter_calibration_config.csv
   obs_config_file: observations_config.csv
   states_config_file: states_config.csv
   depth_model_sd_config_file: depth_model_sd.csv
default_init:
   lake_depth: 6.0  #not a modeled state
   temp: [10.20,10.20,10.20,10.20]
   temp_depths: [1.0,3.0,4.0,6.0]
   salinity: 0.25
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
inflow:
   include_inflow: FALSE
   use_forecasted_inflow: FALSE
   forecast_inflow_model: inflow/FLOWS-NOAAGEFS-AR1/ALEX/0
   observed_inflow_filename: ALEX-targets-inflow.csv
   inflow_variables: [time, FLOW, TEMP, SALT]
   use_ler_vars: FALSE
met:
   use_forecasted_met: TRUE
   use_observed_met: FALSE
   local_directory: drivers/noaa/gefs-v12/stage2/parquet
   observed_met_filename: ALEX-targets-insitu.csv
   use_ler_vars: FALSE
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   met_downscale: TRUE
   inflow_process: TRUE
output_settings:
   diagnostics_names:  [extc]
   evaluate_past: TRUE
   variables_in_scores: [state, parameter]
