file_path:
   qaqc_data_directory: .na
   noaa_directory: .na
   inflow_directory: .na
   configuration_directory: .na
   execute_directory: .na
   forecast_output_directory: .na
location:
   site_id: ALEX
   name: Lake Alexandrina
   latitude: -35   #Degrees North
   longitude: 138  #Degrees East
metadata:
   generate_eml: TRUE
   forecast_project_id: test
   abstract: "This is where a longer description of the forecast can be added"
   forecast_title: FLARE
   intellectualRights: MIT
   model_description:
      forecast_model_id: https://github.com/rqthomas/flare/commit/d1ddcb07b9d28863890597503fc4aa4a4496de56
      name: General Lake Model
      type: process-based
      repository: https://github.com/AquaticEcoDynamics/GLM/releases/tag/v3.1.0
   me:
      individualName:
         givenName: "Quinn"
         surName: "Thomas"
      electronicMailAddress:  "INSERT"
      id: INSERT ORCID
da_setup:
    da_method: enkf
    par_fit_method: inflate
    ensemble_size:  100
    localization_distance: .na #distance in meters were covariances in the model error are used
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    use_obs_constraint: TRUE
model_settings:
   ncore: 8
   model_name: glm
   base_GLM_nml: glm3.nml
   modeled_depths: [0.0, 0.25, 0.50, 0.75, 1.0,
                    1.25, 1.50, 1.75, 2.0,
                    2.25, 2.50, 2.75, 3.0,
                    3.25, 3.50, 3.75, 4.0,
                    4.25, 4.50, 4.75, 5.0,
                    5.25, 5.50, 5.75, 6.0]
   par_config_file: parameter_calibration_config.csv
   obs_config_file: observations_config.csv
   states_config_file: states_config.csv
   depth_model_sd_config_file: depth_model_sd.csv
default_init:
   lake_depth: 6.0  #not a modeled state
   temp: [10.20,10.20,10.20,10.20]
   temp_depths: [1.0,3.0,4.0,6.0]
   salinity: 0.25
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
inflow:
   use_forecasted_inflow: FALSE
   forecast_inflow_model: inflow/FLOWS-NOAAGEFS-AR1
met:
   use_forecasted_met: FALSE
   forecast_met_model: noaa/NOAAGEFS_1hr
   historical_met: observed
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   met_downscale: TRUE
   inflow_process: TRUE
output_settings:
   diagnostics_names:  [extc_coef]
