restart_file: .na
start_datetime: 2022-11-10 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-11-19 00:00:00
forecast_horizon: 0.0
sim_name: ALEX_test
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: no
